version: "3.2"
services:
  composer:
    image: composer/composer
    working_dir: /var/www/html
    command: install
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html
    container_name: 'composer'
networks:
  frontend:
  backend:
volumes:
  db_data: {}
